apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{.Values.cluster }}
spec: 
  encryptedData:
    .dockerconfigjson: {{ .Values.provider.pullSecret }}
  template: 
    data: null
    metadata:
      name: {{ .Values.cluster }}-pull-secret
      namespace: '{{ .Values.cluster }}'
    type: kubernetes.io/dockerconfigjson