apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.infraEnv.name }}-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.infraEnv.name }}
spec: 
  data:
  - secretKey: openshiftPullSecret
    remoteRef: 
      key: {{ .Values.externalSecrets.pullSecretRemoteRef }}
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.infraEnv.name }}-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ "{{ .openshiftPullSecret | toString }}" }}   