{{- if .Values.externalSecrets.bmcCredentialsRemoteRef -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster.name }}-bmc-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster.name }}
spec:
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.bmcCredentialsRemoteRef }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster.name }}-bmc-credentials
    creationPolicy: Orphan
{{- end -}}  