## Example Values for ArgoCD Application

## RHACM Provider Name
#rhacmProviderName: aws-techzone

## Cloud (e.g. aws, azure, vsphere, rhocm)
#cloudProvider:
#  name: "aws"

## AWS Required Values
## The name of the AWS Secrets created in KeyStore must match exactly match below, minus the Ref portion
## For example, awsAccessKeyRef, must be labelled awsAccessKey in your KeyStore.

#awsSecrets:
#  awsAccessKeyRef: 88671bfc-14d4-29ad-ab9b-950eaac3808f
#  awsSecretKeyRef: ac307a9e-41fc-23df-2f28-3ce521b971ea
#  awsBaseDomainRef: 3ab49d22-2408-3dd0-3891-7d613f74c293
#  openshiftPullSecretRef: 115f3c37-cd7c-5704-173f-a8a3e1234b2d
#  openshiftSSHPrivateKeyRef: 9f9063e0-1525-2534-cf8e-9c85096c7b3d
#  openshiftSSHPublicKeyRef: 90a961eb-dfd6-dbbc-049f-a532560614f6

## Azure Required Values
## The name of the Azure Secrets created in KeyStore must match exactly match below, minus the Ref portion
## For example, azureOsServicePrincipalRef, must be labelled azureOsServicePrincipal in your KeyStore.

#azureSecrets:
#  azureBaseDomainRef: 015b85fd-67cb-f70c-fa40-20b9b9d3b510
#  azureBaseDomainResourceGroupNameRef: 20061b87-02af-d55a-fdc0-db9477acbe2a
#  azureOsServicePrincipalRef: 4f5caf7a-174c-5890-84b2-d7cffc7a4be7
#  openshiftPullSecretRef: 115f3c37-cd7c-5704-173f-a8a3e1234b2d
#  openshiftSSHPrivateKeyRef: 9f9063e0-1525-2534-cf8e-9c85096c7b3d
#  openshiftSSHPublicKeyRef: 90a961eb-dfd6-dbbc-049f-a532560614f6 